patches: Add patches from AOSP-10 to provide getEssentialRecordsLoaded()
This is necessary since sdm660-common: Update blobs from LA.UM.8.2.r1-06500-sdm660.0 commit
in vendor/xiaomi/sdm660-common repository

Fixes following telephony crash:
05-12 17:02:51.510  2440  2440 E AndroidRuntime: FATAL EXCEPTION: main
05-12 17:02:51.510  2440  2440 E AndroidRuntime: Process: com.android.phone, PID: 2440
05-12 17:02:51.510  2440  2440 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getEssentialRecordsLoaded()Z in class Lcom/android/internal/telephony/uicc/IccRecords; or its super classes (declaration of 'com.android.internal.telephony.uicc.IccRecords' appears in /system/framework/telephony-common.jar)
05-12 17:02:51.510  2440  2440 E AndroidRuntime:        at com.qualcomm.qti.internal.telephony.dataconnection.QtiDcTracker.onRecordsLoadedOrSubIdChanged(QtiDcTracker.java:82)
05-12 17:02:51.510  2440  2440 E AndroidRuntime:        at com.android.internal.telephony.dataconnection.DcTracker$DctOnSubscriptionsChangedListener.onSubscriptionsChanged(DcTracker.java:412)
05-12 17:02:51.510  2440  2440 E AndroidRuntime:        at android.telephony.SubscriptionManager$OnSubscriptionsChangedListener$OnSubscriptionsChangedListenerHandler.handleMessage(SubscriptionManager.java:945)
05-12 17:02:51.510  2440  2440 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
05-12 17:02:51.510  2440  2440 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
05-12 17:02:51.510  2440  2440 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
05-12 17:02:51.510  2440  2440 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-12 17:02:51.510  2440  2440 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
05-12 17:02:51.510  2440  2440 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

Origin: https://github.com/AOSP-10/frameworks_opt_telephony